# Generated by Django 4.2 on 2025-06-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_videorating'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorating',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
