# Generated by Django 4.2 on 2025-06-30 05:52

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_trainerprofile_profile_pic_alter_trainerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videorating',
            unique_together={('student', 'video')},
        ),
        migrations.AddField(
            model_name='videorating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videorating',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
