# Generated by Django 4.2 on 2025-07-03 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_trainerfeedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'ppt', 'pptx', 'doc', 'docx', 'txt'])]),
        ),
    ]
