# Generated by Django 4.2 on 2025-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
