# Generated by Django 4.2 on 2025-07-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_video_video_url_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
